server:
  servlet:
    context-path: /api

spring:
  h2:
    console:
      enabled: false
  #Datasource settings
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devDB
    username: manager
    password: manager

order:
  delete-unpaid-orders-time-execution: 600000 #10 minutes